title: Hengbo Zhu
logo: /assets/img/hengbo.jpg
email: zhuhengbo2018@gmail.com
description: ISCAS, Linux Kernel Developer, Rust beginner
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/files/vaibhav_vikas.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/vaibhavvikas
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/vaibhavvikas
  - name: Projects
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects
  - name: Blogs
    icon: <i class="fa-solid fa-award"></i>
    link: ./blogs
  - name: Certifications
    icon: <i class="fa-solid fa-award"></i>
    link: ./certifications
  - name: Open Source
    icon: <i class="fa-solid fa-ghost"></i>
    link: ./open-source
