title: Hengbo Zhu
logo: /assets/img/hengbo.jpg
email: zhuhengbo2018@gmail.com
phone: +86 13057520552
description: Linux Kernel Developer, Rust beginner, TCP/IP, DPDK, eBPF, SRv6
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Home
    icon: <i class="fa-solid fa-city fa-fw"></i>
    link: https://hubblezzhu.github.io/
  - name: GitHub
    icon: <i class="fa-brands fa-github fa-fw"></i>
    link: https://github.com/hubblezzhu
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin fa-fw"></i>
    link: https://www.linkedin.com/in/hengbo-zhu-9b5a21222/
  - name: Projects
    icon: <i class="fa-solid fa-file-code fa-fw"></i>
    link: ./projects
  - name: Blogs
    icon: <i class="fa-solid fa-blog fa-fw"></i>
    link: ./blogs
  # - name: Open Source
  #   icon: <i class="fa-solid fa-ghost fa-fw"></i>
  #   link: ./open-source
